<?php

namespace AtlanteIt\EmployeeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeTerritoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeTerritoriesRepository extends EntityRepository
{
}
